services:
  forex-dev:
    build: .
    container_name: forex-development
    volumes:
      - .:/app  
    working_dir: /app
    environment:
      - PYTHONPATH=/app:/app/data_handle:/app/features:/app/models:/app/plots:/app/analysis
    command: sleep infinity